### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by AndyGFX** [PixelVision8/GameCreator#44]
Hi,

1) when color is changed in Color editor and pressed save, new palete is not save to image. I don't understand if colors are saved as pixel data or is changed only color palette in png file.

AndyGFX

**Comment by PixelVision8** [comment]
In order to save the colors back to the colors.png you will need to use the export button.

![image](https://user-images.githubusercontent.com/24598054/28007779-cb84d74e-6522-11e7-9cfe-5cdae2e9b00d.png)

This is a little bit confusing and something I need to address when I clean up the tools next month. The Save button only saves the settings. Hope that clears things up?

**Comment by AndyGFX** [comment]
Thanks.

I will try it.

AndyGFX.
